spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dream-ecommerce
    username: postgres
    password: sachin#khushi@1722
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  port: 8080

api:
  prefix: /api/v1
